name: ci
on:
  push:
    branches:
      - docs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'feat:') || startsWith(github.event.head_commit.message, 'fix:')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
            overrides
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - run: mkdocs gh-deploy --remote-branch main
